---

- "lciolecki.virtualenvwrapper"
- src: "geerlingguy.docker"
- src: "azavea.terraform"
- src: "gantsign.visual-studio-code"
- src: "huxoll.azure-cli"
- src: "rattermeyer.git"
- src: "azavea.virtualbox"
- src: "andrewrothstein.vagrant"
- src: "iknite.spotify"
- src: "patrick-hill.franz"
- src: "mashimom.oh-my-zsh"
